---
abstract: 'Simple Graph.pm-like interface for generating XGMML graphs'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Graph::XGMML
name: Graph-XGMML
no_index:
  directory:
    - inc
    - t
requires:
  XML::Writer: 0.604
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Graph-XGMML
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Graph-XGMML
version: 0.01
